/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.simuladorprestamos;

import java.awt.HeadlessException;

/**
 *
 * @author Rich
 */
public class VentanaSimulador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSimulador
     */
    public VentanaSimulador() {
// 1. Cargar diseño moderno antes de iniciar componentes
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception e) { /* Ignorar error de diseño */ }

    // 2. Inicializar componentes (UNA SOLA VEZ)
    initComponents();
    // Creamos el alineador a la izquierda
javax.swing.table.DefaultTableCellRenderer izquierda = new javax.swing.table.DefaultTableCellRenderer();
izquierda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

// Aplicamos a las columnas de dinero (1, 2 y 3)
// La columna 0 es el "Mes", esa puedes dejarla centrada o a la izquierda también
tablaSimulacion.getColumnModel().getColumn(1).setCellRenderer(izquierda); 
tablaSimulacion.getColumnModel().getColumn(2).setCellRenderer(izquierda); 
tablaSimulacion.getColumnModel().getColumn(3).setCellRenderer(izquierda);
// Esto agrega un pequeño espacio vacío a la izquierda para que no toque el borde
izquierda.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
    
    // Crear un renderizador para alinear a la derecha
javax.swing.table.DefaultTableCellRenderer derecha = new javax.swing.table.DefaultTableCellRenderer();
derecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

// Aplicar a las columnas de dinero (1, 2 y 3)
tablaSimulacion.getColumnModel().getColumn(1).setCellRenderer(derecha); // Interés
tablaSimulacion.getColumnModel().getColumn(2).setCellRenderer(derecha); // Capital
tablaSimulacion.getColumnModel().getColumn(3).setCellRenderer(derecha); // Saldo

// Opcional: Centrar la columna del Mes (columna 0)
javax.swing.table.DefaultTableCellRenderer centro = new javax.swing.table.DefaultTableCellRenderer();
centro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
tablaSimulacion.getColumnModel().getColumn(0).setCellRenderer(centro);
    // Personalizar filas intercaladas
tablaSimulacion.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        if (!isSelected) {
            // Filas pares blancas, impares gris muy claro
            c.setBackground(row % 2 == 0 ? java.awt.Color.WHITE : new java.awt.Color(242, 242, 242));
        }
        // Centrar el texto de la columna "Mes"
        if (column == 0) {
            setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        } else {
            setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        }
        return c;
    }
});
    
    // 3. Estética de la ventana
    this.getContentPane().setBackground(java.awt.Color.WHITE);
    this.setLocationRelativeTo(null); 
    this.setTitle(" - Simulador de Créditos");

    // 4. Cargar Icono (Ruta corregida según tus capturas)
    try {
        // Nota: Asegúrate que la carpeta sea 'Recursos' con R mayúscula como se ve en tu árbol de proyecto
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/simuladorprestamos/Recursos/calculadora.png")).getImage());
    } catch (Exception e) {
        System.out.println("Error al cargar icono: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        txtTasa = new javax.swing.JTextField();
        txtMeses = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSimulacion = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Préstamo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Meses");

        txtMonto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMonto.setName("txtMonto"); // NOI18N
        txtMonto.setPreferredSize(new java.awt.Dimension(64, 30));

        txtTasa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTasa.setName("txtTasa"); // NOI18N
        txtTasa.setPreferredSize(new java.awt.Dimension(64, 30));

        txtMeses.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMeses.setName("txtMeses"); // NOI18N
        txtMeses.setPreferredSize(new java.awt.Dimension(64, 30));

        tablaSimulacion.setBackground(new java.awt.Color(204, 204, 204));
        tablaSimulacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mes", "Interés", "Capital", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSimulacion.setName("tablaSimulacion"); // NOI18N
        tablaSimulacion.setSelectionBackground(new java.awt.Color(255, 153, 0));
        tablaSimulacion.setShowGrid(false);
        jScrollPane2.setViewportView(tablaSimulacion);

        jScrollPane1.setViewportView(jScrollPane2);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calcular Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("TABLA DE AMOTIZACIÓN");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tasa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(txtMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(109, 109, 109)
                                .addComponent(jLabel3)
                                .addGap(89, 89, 89)))
                        .addComponent(jButton1)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(244, 244, 244))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
        // Capturar y limpiar datos de las cajas
        String sMonto = txtMonto.getText().trim();
        String sTasa = txtTasa.getText().trim();
        String sMeses = txtMeses.getText().trim();

        // Verificación de seguridad
        if (sMonto.isEmpty() || sTasa.isEmpty() || sMeses.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresa datos en los tres campos.");
            return;
        }

        // Conversión de tipos
        java.math.BigDecimal monto = new java.math.BigDecimal(sMonto);
        double tasa = Double.parseDouble(sTasa);
        int meses = Integer.parseInt(sMeses);

        // Lógica de cálculo
        CalculadoraService calc = new CalculadoraService();
        prestamo p = new prestamo(monto, tasa, meses); // Usando 'prestamo' en minúsculas
        java.math.BigDecimal cuota = calc.calcularCuota(p);

        // Configuración de la tabla
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaSimulacion.getModel();
        modelo.setRowCount(0); 
        // Identificadores de columnas (por si NetBeans los borra al limpiar)
        modelo.setColumnIdentifiers(new Object[]{"Mes", "Interés", "Capital", "Saldo"});

        java.math.BigDecimal saldoActual = monto;
        double tasaMensual = (tasa / 100) / 12;

// Crear el formato: comas para miles, punto para decimales y dos ceros obligatorios
java.text.DecimalFormat df = new java.text.DecimalFormat("Q #,##0.00");

for (int i = 1; i <= meses; i++) {
    java.math.BigDecimal interesMes = saldoActual.multiply(java.math.BigDecimal.valueOf(tasaMensual))
                                                 .setScale(2, java.math.RoundingMode.HALF_UP);
    java.math.BigDecimal capitalMes = cuota.subtract(interesMes);
    saldoActual = saldoActual.subtract(capitalMes);

    // Formatear los valores usando el DecimalFormat
    String interesStr = df.format(interesMes);
    String capitalStr = df.format(capitalMes);
    String saldoStr = (i == meses) ? "Q 0.00" : df.format(saldoActual);

    modelo.addRow(new Object[]{
        i, 
        interesStr, 
        capitalStr, 
        saldoStr
    });
}

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Usa solo números. No uses letras ni comas.");
    }catch (HeadlessException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error técnico: " + e.getMessage());
    }
        // Este error salta si el usuario escribe letras o deja espacios
         catch (Exception e) {
    // Captura cualquier otro error inesperado
    javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSimulador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaSimulacion;
    private javax.swing.JTextField txtMeses;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtTasa;
    // End of variables declaration//GEN-END:variables
}
